sudo: required
service:
- docker
env:
  global:
  - SHA=$(get rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: oznHZuebPeAIQwZY7fDSbPEOg2Z3ldHEEyoxr91Ge+9JoN6UKUBukzsCG8JBy6JmnVJnn+P7G5ge0AHzqEsafsTihcKyMOOnmBgRPWpE5S80Bwo7keogW2hnnKDIZeKsJrRGLxPy01TiT37NyNySoVV60vpNOdEGfYacpgc14WYVzDH2rRgH4cfDN0IYigtjhd/VjXfTWI7FH6YFmri6h6GAxoQUP4nsLYqxIweEmBNAmzC5NHv9OqGXSNaZTlgP/ZSjFHP1f6R+xni1hMp8s9Bnno6pN/FHV5zecJEuYCLiHM7RhJEILt00U5REVEqRd5hk8vGvXlzJVSqpTTJDp6JuTMaJHv7VwI75Hh9WyYvro5iEqZqLaPK4ru2uTd7CQne3MBBILmlfGq4rT5w2tDs8mJv9OG6czvvudhahietSDR9aG3ox+5hG0fYShUjsd3yQ1gzt3vOYWzEFdH2HdQY+M96ZBj8Ud393FvxzfszxgMAx6GTjd2ko6Lq+9ZYzybmXCQsx+cXNbK/g5QIlRRdBwr+0FQaSGB/zAev1txLXapGUeeVpv1ftOnbxJLIT0Ot0z09yTxtwrTobRWgGhsJ7DCCB9jlPkovO0HMtlLUeCCIt7nrt7peEJcpKDjz+PkYX58MOY9CanwMzw1WFV44uMVfW+WLsCIEDD1s79Uk=
before_install:
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project multi-k8s-231619
- gcloud config set compute/zone europe-west2-a
- gcloud container cluster get-credentials multi-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t maunconsultancy/react-test - f ./client/Dockerfile.dev ./client
script:
- docker run maunconsultancy/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
